### ISSUE TITLE
Fullscreen with different resolution

### ISSUE THREAD

**Issue by gjp1311** [MyraUI/Myra#19] opened 2017-06-26 20:48 UTC
Hello!! This GUI framework is awesome! 
In windowed mode, it works just fine. No complaints.
But I'm having a problem when I set my game to run on fullscreen, but with a different resolution from the desktop (Example : My game is 800:600 and my PC is 1360:720)
When I try to click on a button, it doesn't work! Instead, it works as if the button was located in a different location. 
It seems to be a problem with scaling.  I don't know if I'm doing something wrong or if it is a real issue, but I'd ask for your help! Thank you!!
(Sorry for my english, not my primary language)

**Comment by rds1983** [comment] 2017-07-22 09:46
Hi Gabriel.
Thanks for the kind words and sorry for the late response.
Unfortunately, I couldn't reproduce that issue with the latest Myra version (0.5.1.110). If it is still there, could you provide a code sample that reproduces it? Also what MG version do you use?

Thanks!

**Comment by rds1983** [comment] 2019-08-01 03:47
Closing due to old age.

**Closed as completed by rds1983** 2019-08-01 03:47 UTC
